#8  input verification register
MirceaDumitrescu/React-Web-Game pull request #12
Opened 2022-11-01 13:21 UTC by Crannkky

Reimplementing the verification for the inputs because the code was reset.

2022-11-01 13:35 UTC, MirceaDumitrescu requested changes

2022-11-01 13:35 UTC, MirceaDumitrescu commented on frontend/src/pages/register/register.tsx
> +          console.log(data)
remove console logs from code

2022-11-01 13:35 UTC, MirceaDumitrescu commented on frontend/src/pages/register/register.tsx
> +                if (watch('password') != val) {
create a function for this

2022-11-01 13:35 UTC, MirceaDumitrescu commented on frontend/src/pages/register/register.tsx
> +          {errors.confirmPass && errors.confirmPass.type === 'required' && (
Create a function for more complex validations and return the string based on the argument. try to not DRY. ( DONT REPEAT YOURSELF)

2022-11-02 07:47 UTC, MirceaDumitrescu requested changes
You don't have to upload package-lock unless you specifically modify something in it not when its automated generated

2022-11-02 07:47 UTC, MirceaDumitrescu commented on frontend/src/pages/register/register.tsx
>            console.log(data)
Again, remove console logs from code published

2022-11-02 07:47 UTC, MirceaDumitrescu commented on frontend/src/pages/register/register.tsx
> +  const uuid = uuidv4
I think this needs to be const uuid = **uuidv4()**

2022-11-02 08:03 UTC, Crannkky commented on frontend/src/pages/register/register.tsx
> +          console.log(data)
Done!

2022-11-02 08:03 UTC, Crannkky commented on frontend/src/pages/register/register.tsx
> +          {errors.confirmPass && errors.confirmPass.type === 'required' && (
Done!

2022-11-02 08:04 UTC, Crannkky commented on frontend/src/pages/register/register.tsx
> +  const uuid = uuidv4
I modified. It will be fixed in the next commit.

2022-11-02 08:04 UTC, Crannkky commented on frontend/src/pages/register/register.tsx
>            console.log(data)
I removed it. It will be fixed in the next commit.

2022-11-02 12:47 UTC, MirceaDumitrescu requested changes

2022-11-02 12:47 UTC, MirceaDumitrescu commented on frontend/src/pages/login/login.tsx
> +  console.log(watchEmail, watchPassword)
PLEASE FOR THE LOVE OF GOD, STOP ADDING CONSOLE.LOGS in pull requests

2022-11-02 12:47 UTC, MirceaDumitrescu commented on frontend/src/pages/register/register.tsx
> +    console.log(data)
https://media.giphy.com/media/3owypkSIpM8xw6p7W0/giphy.gif

2022-11-03 06:55 UTC, MirceaDumitrescu requested changes

2022-11-03 06:55 UTC, MirceaDumitrescu commented on frontend/src/pages/formGenerator/formGenerator.tsx
> +  const [inputFields, setInputFields] = useState(inputConfigs)
Remove useState and pass the configs as parameters from parent/initial component

2022-11-03 06:55 UTC, MirceaDumitrescu commented on frontend/src/pages/formGenerator/formGenerator.tsx
> +    <div className='card'>
this div si redundant

2022-11-03 06:55 UTC, MirceaDumitrescu commented on frontend/src/pages/formGenerator/formGenerator.tsx
> +          return (
you dont need return here

2022-11-03 06:55 UTC, MirceaDumitrescu commented on frontend/src/pages/formGenerator/formGenerator.tsx
> +        <button type='submit' className='card__form__btn'>
this needs to be a proper useForm hook element. 

Example:      ` <input type="submit" disabled={!isValid} className="form-button"/>`

2022-11-04 06:55 UTC, Crannkky commented on frontend/src/pages/formGenerator/formGenerator.tsx
> +          return (
Removed the console log and return from there.

2022-11-04 06:59 UTC, Crannkky commented on frontend/src/pages/formGenerator/formGenerator.tsx
> +    <div className='card'>
Done. Removed the div from each generator and moved them inside login and register where i call FormGenerator inside this div.

2022-11-04 07:00 UTC, Crannkky commented on frontend/src/pages/formGenerator/formGenerator.tsx
> +  const [inputFields, setInputFields] = useState(inputConfigs)
Done togheter for register. I started working on login.

2022-11-04 07:41 UTC, MirceaDumitrescu requested changes

2022-11-04 07:41 UTC, MirceaDumitrescu commented on frontend/src/App.tsx
> +import FormGenerator from './pages/formGenerator/formGeneratorRegister'
We don't need this import here

2022-11-04 07:41 UTC, MirceaDumitrescu commented on frontend/src/pages/formGenerator/formGeneratorLogin.tsx
> +        <button type='submit' className='card__form__btn'>
Let's disable this button untill all validations/fields are correct

2022-11-04 07:41 UTC, MirceaDumitrescu commented on frontend/src/pages/formGenerator/formGeneratorRegister.tsx
> +import { useForm } from 'react-hook-form'
Just one FormGenerator.Thats the idea of reusable components

2022-11-04 07:41 UTC, MirceaDumitrescu commented on frontend/src/pages/login/config_login.tsx
> +        inputMail: string,
This is not needed, just check the password in the onSubmit function

2022-11-05 01:07 UTC, Crannkky commented on frontend/src/pages/login/config_login.tsx
> +        inputMail: string,
Done! I implemented this in onSubmit. Check the last commit.

2022-11-05 01:07 UTC, Crannkky commented on frontend/src/pages/formGenerator/formGeneratorRegister.tsx
> +import { useForm } from 'react-hook-form'
Done! FormGenerator works in both components.

2022-11-05 01:08 UTC, Crannkky commented on frontend/src/pages/formGenerator/formGeneratorLogin.tsx
> +        <button type='submit' className='card__form__btn'>
Implemented the verification in both register and login. I use alerts for the moment to display error messages that are generated inside onSubmit functions.

2022-11-05 01:08 UTC, Crannkky commented on frontend/src/App.tsx
> +import FormGenerator from './pages/formGenerator/formGeneratorRegister'
Done! Cleaned all the imports inside the components.

2022-11-05 09:45 UTC, MirceaDumitrescu commented on frontend/src/pages/login/config_login.tsx
> +    className: 'card__form__group__input',
card__form-group__input

2022-11-05 09:48 UTC, MirceaDumitrescu requested changes

2022-11-05 09:48 UTC, MirceaDumitrescu commented on frontend/src/pages/login/login.tsx
> +    const userDataParsed: any = JSON.parse(userData)
const userData = JSON.parse( localstorage.getItem('user' || '{}) )

2022-11-05 09:54 UTC, Crannkky commented on frontend/src/pages/login/login.tsx
> +    const userDataParsed: any = JSON.parse(userData)
This is right :)) 
const userData = JSON.parse(localStorage.getItem('user') || '{}')

2022-11-05 09:56 UTC, merged