Form responsiveness - Attempt 1
MirceaDumitrescu/React-Web-Game pull request #30
Opened 2022-11-11 07:03 UTC by Crannkky

I made some adjustment's tot the form's styling so that the design will look nice on any device width.

2022-11-11 07:47 UTC, MirceaDumitrescu requested changes

2022-11-11 07:47 UTC, MirceaDumitrescu commented on frontend/src/pages/login/login.scss
> +    margin: $m-10;
The variables should be name like:
$spacing-medium
$spacing-large

etc..

2022-11-11 07:47 UTC, MirceaDumitrescu commented on frontend/src/pages/login/login.scss
> +      margin-bottom: 0.5rem;
Stay consistent, if we used mostly pixels, let's not switch to rem

2022-11-11 07:47 UTC, MirceaDumitrescu commented on frontend/src/pages/login/login.scss
> +        border: $bs-1 $p-green;
I have no idea what these variables mean. Try to rename them.

2022-11-11 07:47 UTC, MirceaDumitrescu commented on frontend/src/pages/login/login.scss
> +        background-color: black;
why no variable for black ?

2022-11-11 07:47 UTC, MirceaDumitrescu commented on frontend/src/pages/login/login.tsx
>      </div>
I would suggest a structure with only 1 level of BEM naming. Like
form > form__title > form__redirect & form__redirect-link

2022-11-11 07:47 UTC, MirceaDumitrescu commented on frontend/src/pages/register/register.scss
> +@import '../../variables.scss';
Double import

2022-11-11 07:47 UTC, MirceaDumitrescu commented on frontend/src/pages/login/login.scss
>      &__btn {
If the buttons are being reused for all forms , or at least multiple forms, create a small Button component where you have all logic and css so you DONT REPEAT YOURSELF by rewriting css and all of that.

2022-11-11 07:47 UTC, MirceaDumitrescu commented on frontend/src/pages/login/login.tsx
> +        <Link className='card__form__redirect__link' to='/register'>
This would be the register link so name it accordingly

2022-11-11 07:47 UTC, MirceaDumitrescu commented on frontend/src/pages/register/register.tsx
>      </div>
I have noticed there is no accesibility support. Take a look on that.

2022-11-11 07:55 UTC, MirceaDumitrescu commented
@Crannkky 

Let's make this smaller on mobile version, at least same width as the forms and smaller text.

![image](https://user-images.githubusercontent.com/16415899/201292807-747a74c3-7a53-4d58-a46a-eb15bb00ff1d.png)

2022-11-11 08:40 UTC, Crannkky commented on frontend/src/pages/login/login.scss
> +    margin: $m-10;
Done!

2022-11-11 09:01 UTC, Crannkky commented on frontend/src/pages/login/login.scss
> +        border: $bs-1 $p-green;
Done! They are the border settings in pixels.

2022-11-11 10:09 UTC, Crannkky commented on frontend/src/pages/login/login.scss
> +        background-color: black;
Done! Put variables wherever i could use them inside the code.

2022-11-11 10:10 UTC, Crannkky commented on frontend/src/pages/register/register.scss
> +@import '../../variables.scss';
Done!

2022-11-11 12:35 UTC, Crannkky commented on frontend/src/pages/login/login.scss
>      &__btn {
Both buttons have different functionalities but styling is identical. Also the form's styling is identical for both forms so that's why i want to ask if we can use a single scss file for both forms?

2022-11-11 12:43 UTC, Crannkky commented on frontend/src/pages/login/login.tsx
> +        <Link className='card__form__redirect__link' to='/register'>
How should I name it taking into account the fact that i use the same styling in both forms for the redirect button. I mean isn't it pointless to give them specific names taking into account that they only navigate between the forms and they don't have any other functionality besides it?

2022-11-11 12:58 UTC, Crannkky commented on frontend/src/pages/login/login.tsx
>      </div>
Done!

2022-11-12 07:27 UTC, MirceaDumitrescu commented
@Crannkky This was supposed to be smaller only on mobile with smaller font size as well not on desktop preview

![image](https://user-images.githubusercontent.com/16415899/201462758-5e3fbbed-5718-4a38-89bf-bb890ad41b13.png)

2022-11-12 07:30 UTC, MirceaDumitrescu commented on frontend/src/pages/login/login.tsx
> +        <Link className='card__form__redirect__link' to='/register'>
In this exact situation that button represents `Missing an account? Register here!`

So as i mentioned above in another comment, try to keep only one level of BEM naming and give more specific naming. In this case it should be something like this: (also, you don't need a wrapper div for the Link element)

`    <div className='card'>
      <h4 className='card__title'>Login Form</h4>
      <FormGenerator inputConfigs={inputConfigs} onSubmit={onSubmit}></FormGenerator>
        <Link className='card__button' to='/register'>
          Missing an account? Register here!
        </Link>
    </div>`

2022-11-12 07:31 UTC, MirceaDumitrescu commented on frontend/src/pages/login/login.scss
>      &__btn {
/components/Button.tsx -> renders a button and receives two parameters, for example: button text and on click function. This has button.scss and its the same wherever you use it

2022-11-12 07:31 UTC, MirceaDumitrescu commented on frontend/src/pages/login/login.tsx
>      </div>
I don't see where?

2022-11-12 07:34 UTC, MirceaDumitrescu requested changes

2022-11-12 07:34 UTC, MirceaDumitrescu commented on frontend/src/variables.scss
> +$upper: uppercase;
YOu dont need variables for this. Use variables for dynamic sizes not static text

2022-11-12 07:34 UTC, MirceaDumitrescu commented on frontend/src/pages/register/register.scss
>        font-family: $ff-menu;
what is ff-menu ? What font-family does it represent? Is that default one? Be more specific in naming

2022-11-12 07:34 UTC, MirceaDumitrescu commented on frontend/src/pages/register/register.scss
> +        border: $border-1 $p-green;
What is $p-green ? What does the letter P come frome ?

2022-11-14 08:10 UTC, Crannkky commented on frontend/src/pages/register/register.scss
> +        border: $border-1 $p-green;
Done! Modified the names of the variables as 'primary-color", 'accent-color', 'transparent-color'.

2022-11-14 08:10 UTC, Crannkky commented on frontend/src/variables.scss
> +$upper: uppercase;
Done!

2022-11-14 08:17 UTC, MirceaDumitrescu requested changes

2022-11-14 08:17 UTC, MirceaDumitrescu commented on frontend/src/variables.scss
>    justify-content: $justify-content;
What is the purpose of this?

2022-11-14 08:20 UTC, MirceaDumitrescu commented
@Crannkky on wide screen this looks bad

<img width="875" alt="image" src="https://user-images.githubusercontent.com/16415899/201609969-397ad471-739d-4aa0-9e6f-7a9656fe0e39.png">

2022-11-14 08:29 UTC, Crannkky commented
This is only temporary. I didn t style anything specific here.

2022-11-14 08:49 UTC, Crannkky commented on frontend/src/variables.scss
>    justify-content: $justify-content;
It's a variable for the mixin and i put justify content because it can be used in both grid and flex.

2022-11-14 08:50 UTC, Crannkky commented on frontend/src/pages/login/login.scss
>      &__btn {
Okk, I will implement it and come back with a commit once it's done.

2022-11-14 09:19 UTC, MirceaDumitrescu commented on frontend/src/variables.scss
>    justify-content: $justify-content;
There is no point in creating a variable with the same name for something that never changes....

2022-11-15 08:04 UTC, closed without merging