Feature/character selection creation page
MirceaDumitrescu/React-Web-Game pull request #42
Opened 2022-11-23 18:36 UTC by Crannkky

2022-11-24 06:37 UTC, MirceaDumitrescu requested changes

2022-11-24 06:37 UTC, MirceaDumitrescu commented on frontend/src/pages/character-creation/character-creation.scss
> +}
No responsive? Mobile first design please

2022-11-24 06:37 UTC, MirceaDumitrescu commented on frontend/src/pages/character-creation/chracter-creation.tsx
> +
This file has alot of DRY breaking rules. You are repeating alot of code and hardcoding alot of variables. Try to find a way to modularize this and make it more dynamic.

2022-11-24 06:37 UTC, MirceaDumitrescu commented on frontend/src/routes.tsx
> +    path: '/charSelect',
Usually paths are char-create or char-select not camel case in URL naming

2022-11-26 08:20 UTC, Crannkky commented on frontend/src/routes.tsx
> +    path: '/charSelect',
Done! Modified the paths. They will be inside the next commit.

2022-12-01 06:59 UTC, MirceaDumitrescu requested changes
<img width="631" alt="image" src="https://user-images.githubusercontent.com/16415899/204986417-0802fbd8-3fd2-4732-ae03-511f1ddad80a.png">

These change size when value changes within them

<img width="402" alt="image" src="https://user-images.githubusercontent.com/16415899/204986511-d8d6ecf0-a12e-41ae-8c7e-51c1e9ebc534.png">

What is the purpose of this?

2022-12-01 06:59 UTC, MirceaDumitrescu commented on frontend/src/pages/character-creation/character-creation.scss
> +@media (max-width: 1100px) {
The media can be included in the .char class from the beginning.

.char { 
   // code here
 media@ here
}

2022-12-01 06:59 UTC, MirceaDumitrescu commented on frontend/src/pages/character-creation/chracter-creation.tsx
> +//     </div>
Remove the comments

2022-12-01 10:05 UTC, Crannkky commented on frontend/src/pages/character-creation/character-creation.scss
> +@media (max-width: 1100px) {
The div with character here is substitute at the moment for a character preview where we will display the character's sprite depending on the class that the user selects so that they can view how their character will look like. 
I know the size of the div's change when the stats are changed, same behaviour appears at the button too. 
I will find a way to implement a fix without wrecking the responsiveness.
I will move the media querries inside their corresponding elements at the next commit.

2022-12-01 10:05 UTC, Crannkky commented on frontend/src/pages/character-creation/chracter-creation.tsx
> +//     </div>
Done! They will not be there at the next commit.

2022-12-01 10:10 UTC, Crannkky commented on frontend/src/pages/character-creation/character-creation.scss
> +@media (max-width: 1100px) {
I tried including the media querries inside the char class but it doesn't read the media querries for the container. This means that the character preview div doesn't go beneath the character configuration div and wrecks the responsiveness.
I will commit the correct code maybe you can try something and tell me if I did something wrong?

2022-12-01 10:19 UTC, MirceaDumitrescu approved these changes

2022-12-02 07:10 UTC, merged