Update: started the first issue
MirceaDumitrescu/React-Web-Game pull request #5
Opened 2022-10-31 11:14 UTC by Crannkky

1. Created the pages folder
2. I added the login and register folders inside the pages folder. Still need to add the full files layout inside the coresponding folders. only tsx components are created at the moment.
3. Created the forms using jsx inside login/register
4. Created the styles folder and i created some basic scss set-up and a small reset. Need to start adding actual scss inside.

2022-10-31 13:17 UTC, MirceaDumitrescu requested changes

2022-10-31 13:17 UTC, MirceaDumitrescu commented on frontend/package.json
> +    "sass": "^1.55.0",
Why do you need this package?

2022-10-31 13:17 UTC, MirceaDumitrescu commented on frontend/public/index.html
> +    <link rel="preconnect" href="https://fonts.googleapis.com" />
Pls import fonts via scss as variables not html

2022-10-31 13:17 UTC, MirceaDumitrescu commented on frontend/src/pages/login/login.tsx
> +    <div className='flex-col'>
Please use BEM class naming

2022-10-31 13:17 UTC, MirceaDumitrescu commented on frontend/src/pages/register/register.tsx
> +    <div className='container flex-col'>
BEM

2022-10-31 13:18 UTC, MirceaDumitrescu requested changes

2022-10-31 13:18 UTC, MirceaDumitrescu commented on frontend/src/variables.scss
> +.grid-2 {
Try replacing all 4 grids with 1 SCSS mixin with parameters

2022-10-31 13:26 UTC, Crannkky commented on frontend/package.json
> +    "sass": "^1.55.0",
I installed it because when i tried adding the scss in any files i received errors which i can't remember exactly now. After installation everything was ok.

2022-10-31 16:52 UTC, Crannkky commented on frontend/public/index.html
> +    <link rel="preconnect" href="https://fonts.googleapis.com" />
Done!

2022-10-31 17:08 UTC, Crannkky commented on frontend/src/variables.scss
> +.grid-2 {
Done! There are 2 mixins now one to cover the flex scenarios and one to cover the grid scenarios

2022-10-31 17:37 UTC, Crannkky commented on frontend/src/pages/register/register.tsx
> +    <div className='container flex-col'>
Done!

2022-10-31 17:37 UTC, Crannkky commented on frontend/src/pages/login/login.tsx
> +    <div className='flex-col'>
Done!

2022-11-01 01:27 UTC, MirceaDumitrescu requested changes

2022-11-01 01:27 UTC, MirceaDumitrescu commented on frontend/src/pages/login/login.tsx
> +    <div className='form__container'>
if the parent is form__container, than all children must have form__container__submit, not just form

2022-11-01 01:27 UTC, MirceaDumitrescu commented on frontend/src/pages/register/register.scss
> +  .form__submit {
if you respect BEM, then this can be written with the & sign
<img width="754" alt="image" src="https://user-images.githubusercontent.com/16415899/199138618-2e7d5079-3c47-4560-ba54-b80a9bba4c4b.png">

2022-11-01 08:25 UTC, MirceaDumitrescu approved these changes

2022-11-01 08:25 UTC, merged